// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type InputLogin struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type InputRegisterUser struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type InputUpdateUser struct {
	Email              string `json:"email"`
	Password           string `json:"password"`
	IsActive           bool   `json:"isActive"`
	FirstName          string `json:"firstName"`
	LastName           string `json:"lastName"`
	AdditionalName     string `json:"additionalName"`
	ProfileImageURL    string `json:"profileImageUrl"`
	BackgroundImageURL string `json:"backgroundImageUrl"`
	Pronouns           string `json:"pronouns"`
	Headline           string `json:"headline"`
	About              string `json:"about"`
	Country            string `json:"country"`
	City               string `json:"city"`
	ProfileLink        string `json:"profileLink"`
}

type User struct {
	ID                 string `json:"id"`
	Email              string `json:"email"`
	Password           string `json:"password"`
	IsActive           bool   `json:"isActive"`
	FirstName          string `json:"firstName"`
	LastName           string `json:"lastName"`
	AdditionalName     string `json:"additionalName"`
	ProfileImageURL    string `json:"profileImageUrl"`
	BackgroundImageURL string `json:"backgroundImageUrl"`
	Pronouns           string `json:"pronouns"`
	Headline           string `json:"headline"`
	About              string `json:"about"`
	Country            string `json:"country"`
	City               string `json:"city"`
	ProfileLink        string `json:"profileLink"`
}
