// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Block struct {
	UserID  string `json:"userId"`
	BlockID string `json:"blockId"`
}

type CreateJob struct {
	Title          string `json:"title"`
	CompanyName    string `json:"companyName"`
	Workplace      string `json:"workplace"`
	City           string `json:"city"`
	Country        string `json:"country"`
	EmploymentType string `json:"employmentType"`
	Description    string `json:"description"`
}

type Hastag struct {
	ID     string `json:"id"`
	Hastag string `json:"hastag"`
}

type InputEducation struct {
	UserID         string `json:"userId"`
	School         string `json:"school"`
	Degree         string `json:"degree"`
	FieldStudy     string `json:"fieldStudy"`
	Grade          string `json:"grade"`
	Activities     string `json:"activities"`
	Description    string `json:"description"`
	MonthStartDate string `json:"monthStartDate"`
	MonthEndDate   string `json:"monthEndDate"`
	YearStartDate  string `json:"yearStartDate"`
	YearEndDate    string `json:"yearEndDate"`
}

type InputExperience struct {
	UserID         string `json:"userId"`
	Title          string `json:"title"`
	EmploymentType string `json:"employmentType"`
	CompanyName    string `json:"companyName"`
	Country        string `json:"country"`
	City           string `json:"city"`
	IsActive       bool   `json:"isActive"`
	Industry       string `json:"industry"`
	MonthStartDate string `json:"monthStartDate"`
	MonthEndDate   string `json:"monthEndDate"`
	YearStartDate  string `json:"yearStartDate"`
	YearEndDate    string `json:"yearEndDate"`
}

type InputLogin struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type InputPost struct {
	SenderID string `json:"senderId"`
	Text     string `json:"text"`
	PhotoURL string `json:"photoUrl"`
	VideoURL string `json:"videoUrl"`
}

type InputRegisterUser struct {
	Email           string `json:"email"`
	Password        string `json:"password"`
	FirstName       string `json:"firstName"`
	LastName        string `json:"lastName"`
	Country         string `json:"country"`
	City            string `json:"city"`
	Headline        string `json:"headline"`
	ProfileImageURL string `json:"profileImageUrl"`
}

type InputUpdateUser struct {
	Email              string `json:"email"`
	Password           string `json:"password"`
	IsActive           bool   `json:"isActive"`
	FirstName          string `json:"firstName"`
	LastName           string `json:"lastName"`
	ProfileImageURL    string `json:"profileImageUrl"`
	BackgroundImageURL string `json:"backgroundImageUrl"`
	Pronouns           string `json:"pronouns"`
	Headline           string `json:"headline"`
	About              string `json:"about"`
	Country            string `json:"country"`
	City               string `json:"city"`
	ProfileLink        string `json:"profileLink"`
}

type Job struct {
	ID             string    `json:"id"`
	Title          string    `json:"title"`
	CompanyName    string    `json:"companyName"`
	Workplace      string    `json:"workplace"`
	City           string    `json:"city"`
	Country        string    `json:"country"`
	EmploymentType string    `json:"employmentType"`
	Description    string    `json:"description"`
	CreatedAt      time.Time `json:"createdAt"`
}

type Search struct {
	Users []*User `json:"Users"`
	Posts []*Post `json:"Posts"`
}
